server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/chandanp11/microservicecourse-config.git"
        #native:
          #search-locations: "file:///Users//chandanp//mydata//config"
          #search-locations: "classpath:/config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true