services:
    accounts:
      image: "chandanp11/accounts:s4"
      container_name: accounts-ms
      ports:
        - "8080:8080"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - myNetwork
    loans:
      image: "chandanp11/loans:s4"
      container_name: loans-ms
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - myNetwork
    cards:
      image: "chandanp11/cards:s4"
      container_name: cards-ms
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: 700m
      networks:
        - myNetwork
networks:
  myNetwork:
    driver: bridge