spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "3.1"

cards:
  message: "welcome to Chandan's CARDs related local APIs"
  contactDetails:
    name: "Cards Developer - Default"
    email: "chandan.p11@gmail.com"
  onCallSupport:
    - 123456789
    - 987654321
